/**
 * /help command - Show command help
 */

import type { CommandDefinition, CommandContext, CommandResult, ParsedCommand } from '@/commands/types';

export const helpCommand: CommandDefinition = {
  name: 'help',
  aliases: ['h', '?'],
  description: 'Show available commands and help information',
  category: 'system',
  usage: '/help [category|command]',
  examples: [
    '/help',
    '/help social',
    '/help say',
  ],

  parameters: {
    positional: [
      {
        type: 'string',
        required: false,
        description: 'Category or command name',
      },
    ],
  },

  handler: async (context: CommandContext, args: ParsedCommand): Promise<CommandResult> => {
    const query = args.positionalArgs[0];

    // Help text will be generated by CommandExecutor using CommandRegistry
    // This is just a placeholder that triggers help display
    return {
      success: true,
      data: {
        helpQuery: query || 'general',
      },
      events: [
        {
          type: 'help_request',
          data: {
            query: query || 'general',
            characterId: context.characterId,
          },
        },
      ],
    };
  },
};
